# constants.py

classes = {
    0: 'Speed limit (20km/h)',
    1: 'Speed limit (30km/h)',
    2: 'Speed limit (50km/h)',
    3: 'Speed limit (60km/h)',
    4: 'Speed limit (70km/h)',
    5: 'Speed limit (80km/h)',
    6: 'End of speed limit (90km/h)',
    7: 'Speed limit (100km/h)',
    8: 'Speed limit (120km/h)',
    9: 'No passing zone',
    10: 'No passing for vehicles with a total weight of over 3.5 t.',
    11: 'Upcoming intersection or crossing',
    12: 'Priority Road starts',
    13: 'Right of Way',
    14: 'Stop and yield',
    15: 'No entry for any type of Vehicle',
    16: 'No entry for motor vehicles with a maximum authorized mass of more than 3.5 t.',
    17: 'Do not enter',
    18: 'General danger or warning sign',
    19: 'A single curve is approaching in the left direction',
    20: 'A single curve is approaching in the right direction',
    21: 'Indicates an approaching double curve - first to the left.',
    22: 'Warning of a rough road ahead.',
    23: 'Danger of skidding or slipping',
    24: 'The road narrows from the right side.',
    25: 'Work in process.',
    26: 'Indicates the traffic signal ahead.',
    27: 'Pedestrians may cross the road - installation on the right side of the road.',
    28: 'Pay attention to children - installation on the right side of the road.',
    29: 'Be aware of cyclists, - installation on the right side of the road.',
    30: 'Beware of an icy road ahead.',
    31: 'Indicates wild animals may cross the road.',
    32: 'End of all previously set passing and speed restrictions.',
    33: 'Indicates that traffic must turn right (after the signboard).',
    34: 'Indicates that traffic must turn left (after the signboard).',
    35: 'The mandatory direction of travel is straight ahead. No turns are permitted.',
    36: 'Mandatory directions of travel, straight ahead or right (after the signboard).',
    37: 'Mandatory directions of travel, straight ahead or left (after the signboard).',
    38: 'Prescribed drive direction around the obstacle. Drive from the right of the obstacle.',
    39: 'Prescribed drive direction around the obstacle. Drive from the left of the obstacle.',
    40: 'Indicates entrance to a traffic circle (roundabout).',
    41: 'End of the no-passing zone.',
    42: 'End of no passing by vehicles over 3.5 metric tons'
}
